### ISSUE TITLE
 Caused by: java.lang.RuntimeException: Cannot create an instance of class com.akshay.newsapp.news.ui.viewmodel.NewsArticleViewModel

### ISSUE THREAD

**Issue by akash09766** [AkshayChordiya/News#33]
gettting below error at first launch after import in to android studio

2020-02-27 15:16:26.804 23096-23096/com.akshay.newsapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.akshay.newsapp, PID: 23096
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.akshay.newsapp/com.akshay.newsapp.news.ui.activity.NewsActivity}: java.lang.RuntimeException: Cannot create an instance of class com.akshay.newsapp.news.ui.viewmodel.NewsArticleViewModel
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2952)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3087)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1817)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6746)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.RuntimeException: Cannot create an instance of class com.akshay.newsapp.news.ui.viewmodel.NewsArticleViewModel
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:221)
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:278)
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:106)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at com.akshay.newsapp.news.ui.activity.NewsActivity$newsArticleViewModel$2.invoke(NewsActivity.kt:50)
        at com.akshay.newsapp.news.ui.activity.NewsActivity$newsArticleViewModel$2.invoke(NewsActivity.kt:18)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.akshay.newsapp.news.ui.activity.NewsActivity.getNewsArticleViewModel(Unknown Source:7)
        at com.akshay.newsapp.news.ui.activity.NewsActivity.onCreate(NewsActivity.kt:39)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2932)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3087) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1817) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6746) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.InstantiationException: java.lang.Class<com.akshay.newsapp.news.ui.viewmodel.NewsArticleViewModel> has no zero argument constructor
        at java.lang.Class.newInstance(Native Method)
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:219)
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:278) 
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:106) 
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185) 
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150) 
        at com.akshay.newsapp.news.ui.activity.NewsActivity$newsArticleViewModel$2.invoke(NewsActivity.kt:50) 
        at com.akshay.newsapp.news.ui.activity.NewsActivity$newsArticleViewModel$2.invoke(NewsActivity.kt:18) 
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) 
        at com.akshay.newsapp.news.ui.activity.NewsActivity.getNewsArticleViewModel(Unknown Source:7) 
        at com.akshay.newsapp.news.ui.activity.NewsActivity.onCreate(NewsActivity.kt:39) 
        at android.app.Activity.performCreate(Activity.java:7144) 
        at android.app.Activity.performCreate(Activity.java:7135) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2932) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3087) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1817) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6746) 
        at java.lang.reflect.Method.invoke(Native Method)

**Comment by AkshayChordiya** [comment]
Can you please try the latest master and let me know if that works for you?
Thanks

**Comment by akash09766** [comment]
working now....

how can i add support for fragment.
I have created BaseFargment just like BaseActivity and some other same just like activity i am getting below error.

   Process: com.skylightdevelopers.android.moviemaasala, PID: 10270
    kotlin.UninitializedPropertyAccessException: lateinit property viewModelFactory has not been initialized
        at com.skylightdevelopers.android.moviemaasala.core.ui.base.DaggerFragment.getViewModelFactory(DaggerFragment.kt:24)
        at com.skylightdevelopers.android.moviemaasala.app.fragment.NewReleasedFragment$newReleasedViewModel$2.invoke(NewReleasedFragment.kt:66)
        at com.skylightdevelopers.android.moviemaasala.app.fragment.NewReleasedFragment$newReleasedViewModel$2.invoke(NewReleasedFragment.kt:17)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.skylightdevelopers.android.moviemaasala.app.fragment.NewReleasedFragment.getNewReleasedViewModel(Unknown Source:7)
        at com.skylightdevelopers.android.moviemaasala.app.fragment.NewReleasedFragment.setObserver(NewReleasedFragment.kt:41)
        at com.skylightdevelopers.android.moviemaasala.app.fragment.NewReleasedFragment.onActivityCreated(NewReleasedFragment.kt:36)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2717)
        at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1188)
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2224)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1997)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1953)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2629)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2722)
        at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1188)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1392)
        at android.app.Activity.performStart(Activity.java:7165)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2976)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1817)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6746)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by akash09766** [comment]
Now Its build working.
if i want to add support for fragment then, is it right approach ?

inline fun <reified T : ViewModel> Fragment.getViewModel(): T {
    return ViewModelProvider(this, (activity as BaseActivity).viewModelFactory).get(T::class.java)
}

**Comment by akash09766** [comment]
found it.
Actually i was implementing HasAndroidInjector  instead of Injectable in BaseFragment.

**Comment by AkshayChordiya** [comment]
Yeah you need to implement the `Injectable` interface. Maybe we can only rely on `HasAndroidInjector`, I'll take a look to update if possible.

Just so you know there is a difference between getting view model:
```
// View model is scoped to parent activity
inline fun Fragment.getViewModel(): T {
   return ViewModelProvider(this.activity, (activity as BaseActivity).viewModelFactory).get(T::class.java)
}

// View model is scoped to fragment
inline fun Fragment.getViewModel(): T {
   return ViewModelProvider(this, (activity as BaseActivity).viewModelFactory).get(T::class.java)
}
```
